table _Measures
	lineageTag: 9de6a2ca-f66a-4e57-8498-7cc90ab61324

	measure 'Journey Count' =
			
			CALCULATE(COUNTROWS(Railway))
		formatString: #,0
		lineageTag: 2680a762-037e-484a-9ebb-1d046a35777e

	measure 'Top Routes' = ```
			
			VAR _top =
			CALCULATE(
			    [Journey Count],
			    KEEPFILTERS(
			        TOPN(
			            [Top Routes Value],
			            ALLSELECTED(DimRoute[Journey Route] ),
			            CALCULATE([Journey Count], ALLSELECTED(DimRoute[Direction])),
			            DESC,
			            [Journey Count],
			            DESC,
			            DimRoute[Journey Route],
			            DESC
			        )
			    )
			)
			VAR _bottom=
			CALCULATE(
			    [Journey Count],
			    KEEPFILTERS(
			        TOPN(
			            [Top Routes Value],
			            ALLSELECTED(DimRoute[Journey Route], DimRoute[Direction]),
			            CALCULATE([Journey Count], ALLSELECTED(DimRoute[Direction])),
			            ASC, 
			            [Journey Count],
			            ASC,                    
			            DimRoute[Journey Route],
			            ASC
			        )
			    )
			)
			VAR _Result =
			    IF(SELECTEDVALUE(TopBottom[Order]) ="Top", _top, _bottom)
			
			RETURN
			    _Result
			```
		formatString: 0
		lineageTag: 287539a1-9c78-4e5d-a1a8-134ee4c93249

	measure 'Peak Travel Times' =
			
			CALCULATE(
			    [Journey Count],
			    USERELATIONSHIP('Time'[Time to the Minute], Railway[Departure Time])
			)
		formatString: 0
		lineageTag: 3eec4a8a-a38e-496e-a4c9-34b5f7a5ecb4

	measure 'Peak Travel Times Conditional Formatting' = ```
			
			VAR TimeSlotRanking = 
			CALCULATE(RANKX(
			    ALLSELECTED('Time'[30 mins time slot]),
			    [Peak Travel Times],
			    ,
			    DESC
			))
			RETURN
			IF(TimeSlotRanking <= 3, "Red", "LightBlue")
			
			```
		lineageTag: 9996f139-37c6-46fb-aeb2-35cf6f1f3778

	measure 'Cancellation Percentage' = ```
			
			VAR CancelledJourneys = 
			CALCULATE(
			    COUNTROWS(Railway),
			    DimJourney[Journey Status] = "Cancelled"
			)
			RETURN
			DIVIDE(
			    CancelledJourneys,
			    [Journey Count],
			    0
			)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 76983613-ff94-4d72-aec8-85b0bef68cda

	measure 'Top Cancelled Routes' = ```
			
			VAR _top =
			CALCULATE(
			    [Journey Count],
			    KEEPFILTERS(
			        TOPN(
			            [Top Routes Value],
			            ALLSELECTED(DimRoute[Journey Route]),
			            CALCULATE([Cancellation Percentage], ALLSELECTED(DimJourney)),
			            DESC,
			            [Cancellation Percentage],
			            DESC,
			            DimRoute[Journey Route],
			            DESC
			        )
			    )
			)
			VAR _bottom =
			CALCULATE(
			    [Journey Count],
			    KEEPFILTERS(
			        TOPN(
			            [Top Routes Value],
			            ALLSELECTED(DimRoute[Journey Route]),
			            [Cancellation Percentage],
			            ASC,
			            CALCULATE([Cancellation Percentage], ALLSELECTED(DimJourney)),            
			            ASC,
			            DimRoute[Journey Route],
			            ASC
			        )
			    )
			)
			VAR _Result =
			    IF(SELECTEDVALUE(TopBottom[Order]) ="Top", _top, _bottom)
			RETURN
			    _Result
			```
		formatString: 0
		lineageTag: 57e788ea-3dbc-4eed-9ee7-fc92e723705f

	measure 'Delayed Percentage' = ```
			
			VAR DelayedJourneys = 
			CALCULATE(
			    COUNTROWS(Railway),
			    DimJourney[Journey Status] = "Delayed"
			)
			RETURN
			DIVIDE(
			    DelayedJourneys,
			    [Journey Count],
			    0
			)
			```
		lineageTag: 38643d20-7fc8-4e05-b572-e3919fe2c211

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top Delayed Routes' =
			
			VAR _top =
			CALCULATE(
			    [Journey Count],
			    KEEPFILTERS(
			        TOPN(
			            [Top Routes Value],
			            ALLSELECTED(DimRoute[Journey Route]),
			            CALCULATE([Delayed Percentage], ALLSELECTED(DimJourney)),
			            DESC,
			            [Delayed Percentage],
			            DESC,
			            DimRoute[Journey Route],
			            DESC
			        )
			    )
			)
			VAR _bottom =
			CALCULATE(
			    [Journey Count],
			    KEEPFILTERS(
			        TOPN(
			            [Top Routes Value],
			            ALLSELECTED(DimRoute[Journey Route]),
			            CALCULATE([Delayed Percentage], ALLSELECTED(DimJourney)),
			            ASC,
			            [Delayed Percentage],
			            ASC,
			            DimRoute[Journey Route],
			            ASC
			        )
			    )
			)
			
			VAR _Result =
			    IF(SELECTEDVALUE(TopBottom[Order]) ="Top", _top, _bottom)
			RETURN
			    _Result
		formatString: 0
		lineageTag: 595e788f-8d87-4c2f-96d6-01638ba30acc

	measure 'Average Number of Trips by Day of Week' =
			
			AVERAGEX(
			    VALUES('Date'[Date]),
			    [Journey Count]
			)
		formatString: 0
		lineageTag: c4b790da-a3c4-4b83-b193-e782488c2b92

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Average Number of Trips by Time' =
			
			AVERAGEX(
			    VALUES('Time'[Time to the Minute]),
			    [Journey Count]
			)
		lineageTag: cd4c2fe2-acd5-4e99-90c8-33f061d5aa20

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Ticket Booked' =
			
			CALCULATE(SUM(Railway[Price]))
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 09ceb4c5-08c1-4a1f-9feb-acf605d75ed5

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Total Ticket Refunded' =
			
			CALCULATE(
			    [Total Ticket Booked],
			    DimJourney[Refund] = "Yes"
			)
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 8e9c83cc-3e20-4b70-b1ea-ab7583ce79bd

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Total Ticket Net' =
			
			[Total Ticket Booked] - [Total Ticket Refunded]
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 43b6b411-e2af-425e-9955-427c592c7fc3

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Average Delay Time' =
			
			VAR _Result =
			AVERAGEX(
			    VALUES(Railway[Transaction ID]),
			    SUM(Railway[Late Arrival Duration])
			)
			RETURN
			    IF(_Result = BLANK(), 0,_Result)
		lineageTag: b8da3aee-4150-4dcb-b017-34520244b2ca

		formatStringDefinition = "0 minutes"

	measure 'Cancelled Journeys' =
			
			CALCULATE(
			    COUNTROWS(Railway),
			    DimJourney[Journey Status] = "Cancelled"
			)
		formatString: #,0
		lineageTag: 6dd6cd97-d2e1-4c0e-90d4-397c4b207099

	measure 'Delayed Journeys' =
			
			CALCULATE(
			    COUNTROWS(Railway),
			    DimJourney[Journey Status] = "Delayed"
			)
		formatString: #,0
		lineageTag: 795a85a6-0916-4423-8c88-95d9b3eadfc7

	measure 'PM Trips' =
			
			CALCULATE(
			    [Journey Count],
			    DATEADD('Date'[Date], -1,MONTH))
		formatString: #,0
		lineageTag: 6031f9a8-35c4-4da0-bae2-c7b150f2dfd2

	measure 'Percentage Difference (Trips)' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR _current = [Journey Count]
			VAR _previous = [PM Trips]
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, down_arrow & " " &  FORMAT(_growth, "0.00%"), up_arrow & " " &  FORMAT(_growth, "0.00%"))
		displayFolder: Percentage Difference
		lineageTag: 84882774-b32c-409e-8236-3acace3422de

	measure 'Percentage Difference (Cancelled Trips)' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR _current = [Cancelled Journeys]
			VAR _previous = CALCULATE([Cancelled Journeys], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, down_arrow & " " &  FORMAT(_growth, "0.00%"), up_arrow & " " &  FORMAT(_growth, "0.00%"))
		displayFolder: Percentage Difference
		lineageTag: aa6c955f-27ce-420a-95f4-7e6deaa6796c

	measure 'Percentage Difference (Delayed Trips)' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR _current = [Delayed Journeys]
			VAR _previous = CALCULATE([Delayed Journeys], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, down_arrow & " " &  FORMAT(_growth, "0.00%"), up_arrow & " " &  FORMAT(_growth, "0.00%"))
		displayFolder: Percentage Difference
		lineageTag: 91c1bf24-d44b-484a-b5a9-7a1bb23b4ba4

	measure 'Percentage Difference (Delay Time)' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR _current = [Average Delay Time]
			VAR _previous = CALCULATE([Average Delay Time], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, down_arrow & " " &  FORMAT(_growth, "0.00%"), up_arrow & " " &  FORMAT(_growth, "0.00%"))
		displayFolder: Percentage Difference
		lineageTag: b07266a1-b718-4d48-82ca-45423c1374b9

	measure 'Refunded Journeys' =
			
			CALCULATE(
			    COUNTROWS(Railway),
			    DimJourney[Refund] = "Yes"
			)
		formatString: #,0
		lineageTag: 852b4598-d052-41e6-b011-5fa7ad9124f5

	measure 'Percentage Difference (Refunded Journey)' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR _current = [Refunded Journeys]
			VAR _previous = CALCULATE([Refunded Journeys], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, down_arrow & " " &  FORMAT(_growth, "0.00%"), up_arrow & " " &  FORMAT(_growth, "0.00%"))
		displayFolder: Percentage Difference
		lineageTag: 891129be-12f2-4c38-b301-85e470070ede

	measure 'PM Ticket Sales' =
			
			CALCULATE(
			    [Total Ticket Booked],
			    DATEADD('Date'[Date], -1,MONTH)
			)
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: bb5604c7-739c-444a-853c-1b93607787e1

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Percentage Difference (Ticket Sales)' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR _current = [Total Ticket Booked]
			VAR _previous = CALCULATE([Total Ticket Booked], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, down_arrow & " " &  FORMAT(_growth, "0.00%"), up_arrow & " " &  FORMAT(_growth, "0.00%"))
		displayFolder: Percentage Difference
		lineageTag: f0b35933-e9fe-4c9f-82f7-1ab2a9236e1c

	measure 'Percentage Difference (Refunded Sales)' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR _current = [Total Ticket Refunded]
			VAR _previous = CALCULATE([Total Ticket Refunded], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, down_arrow & " " &  FORMAT(_growth, "0.00%"), up_arrow & " " &  FORMAT(_growth, "0.00%"))
		displayFolder: Percentage Difference
		lineageTag: 64e13c9c-90e0-4109-9c3e-0492fe8fcfc2

	measure 'Percentage Difference (Net Sales)' =
			
			VAR up_arrow = UNICHAR(129137)
			VAR down_arrow = UNICHAR(129139)
			VAR _current = [Total Ticket Net]
			VAR _previous = CALCULATE([Total Ticket Net], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, down_arrow & " " &  FORMAT(_growth, "0.00%"), up_arrow & " " &  FORMAT(_growth, "0.00%"))
		displayFolder: Percentage Difference
		lineageTag: 76570474-5a22-426a-9569-c4a118494b6a

	measure 'Percentage Colour (Trips)' =
			
			VAR _current = [Journey Count]
			VAR _previous = [PM Trips]
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			    IF( _growth <0, "red", "green")
		displayFolder: Percentage Difference\Percentage Colour
		lineageTag: c4bd59e8-8ed8-4163-ae9b-ab64b976aa79

	measure 'Percentage Colour (Cancelled Trips)' =
			
			VAR _current = [Cancelled Journeys]
			VAR _previous = CALCULATE([Cancelled Journeys], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			     IF( _growth <0, "red", "green")
		displayFolder: Percentage Difference\Percentage Colour
		lineageTag: cc0b4a8d-ae18-4d61-9827-c5b2fb1a3753

	measure 'Percentage Colour (Delayed Trips)' =
			VAR _current = [Delayed Journeys]
			VAR _previous = CALCULATE([Delayed Journeys], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			     IF( _growth <0, "red", "green")
		displayFolder: Percentage Difference\Percentage Colour
		lineageTag: d433223e-e602-4675-aab6-c299f1f6cbf8

	measure 'Percentage Colour (Delay Time)' =
			VAR _current = [Average Delay Time]
			VAR _previous = CALCULATE([Average Delay Time], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			     IF( _growth <0, "red", "green")
		displayFolder: Percentage Difference\Percentage Colour
		lineageTag: f76fe76d-6a5c-419f-b81b-97dbc9062db6

	measure 'Percentage Colour (Refunded Journey)' =
			VAR _current = [Refunded Journeys]
			VAR _previous = CALCULATE([Refunded Journeys], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			     IF( _growth <0, "red", "green")
		displayFolder: Percentage Difference\Percentage Colour
		lineageTag: 99ff6026-162b-4a76-a989-dca5b81e70f5

	measure 'Percentage Colour (Ticket Sales)' =
			VAR _current = [Total Ticket Booked]
			VAR _previous = CALCULATE([Total Ticket Booked], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			     IF( _growth <0, "red", "green")
		displayFolder: Percentage Difference\Percentage Colour
		lineageTag: 1b3040a9-b891-4e57-a2d7-6acd2e2f7cea

	measure 'Percentage Colour (Refunded Sales)' =
			VAR _current = [Total Ticket Refunded]
			VAR _previous = CALCULATE([Total Ticket Refunded], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			     IF( _growth <0, "red", "green")
		displayFolder: Percentage Difference\Percentage Colour
		lineageTag: 79fdb720-91f5-420e-ac4c-8b70a5fc97cf

	measure 'Percentage Colour (Net Sales)' =
			VAR _current = [Total Ticket Net]
			VAR _previous = CALCULATE([Total Ticket Net], DATEADD('Date'[Date], -1,MONTH))
			VAR _growth = DIVIDE (_current - _previous, _previous,0)
			RETURN
			     IF( _growth <0, "red", "green")
		displayFolder: Percentage Difference\Percentage Colour
		lineageTag: 0f0d706a-8b75-4deb-9d8e-18197cf5383f

	measure 'Popular Route Chart Title' =
			
			COMBINEVALUES(" ", SELECTEDVALUE(TopBottom[Order]),[Top Routes Value], "Popular Routes")
		lineageTag: 2d1f6e0b-bf2c-4063-9a70-2ae0b30c0dc2

	measure 'Sales Label' =
			
			IF (
			    [Total Ticket Booked]> [PM Ticket Sales],
			    [Total Ticket Booked],
			    [PM Ticket Sales]
			)
		formatString: 0
		lineageTag: b554dd29-39d1-40d1-8dd4-20e1a916e280

	measure 'Cancelled Route Chart Title' =
			
			COMBINEVALUES(" ", SELECTEDVALUE(TopBottom[Order]),[Top Routes Value], "Cancelled Routes")
		lineageTag: 6717a0e8-153f-4888-8989-174f5183fc4e

	measure 'Delayed Route Chart Title' =
			
			COMBINEVALUES(" ", SELECTEDVALUE(TopBottom[Order]),[Top Routes Value], "Delayed Routes")
		lineageTag: e101ef37-43c1-49d3-a1e4-e6503ab92d0e

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

